version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: seo-automation-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass supersecret123
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "supersecret123", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local
